# Generated by Django 2.2.3 on 2019-07-04 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagamodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
