# Generated by Django 2.2.3 on 2019-07-02 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vagamodel',
            options={'ordering': ['dt_modificacao'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AddField(
            model_name='vagamodel',
            name='dt_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vagamodel',
            name='dt_validade',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vagamodel',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vagamodel',
            name='dt_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
