# Generated by Django 2.2.3 on 2019-07-04 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0002_auto_20190703_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagamodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
