# Generated by Django 2.2.3 on 2019-07-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestormodel',
            options={'ordering': ['name'], 'verbose_name': 'Gestor', 'verbose_name_plural': 'Gestores'},
        ),
    ]
