# Generated by Django 2.2.3 on 2019-07-02 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='candidatomodel',
            name='cpf',
            field=models.CharField(default=None, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatomodel',
            name='dt_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatomodel',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em:'),
        ),
        migrations.AddField(
            model_name='candidatomodel',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
