# Generated by Django 2.2.3 on 2019-07-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_auto_20190702_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatomodel',
            options={'ordering': ['name'], 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
    ]
