# Generated by Django 2.2.3 on 2019-07-02 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_auto_20190702_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculomodel',
            options={'ordering': ['name'], 'verbose_name': 'Currículo', 'verbose_name_plural': 'Currículos'},
        ),
        migrations.AddField(
            model_name='curriculomodel',
            name='cpf',
            field=models.CharField(default=1, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculomodel',
            name='dt_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculomodel',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em:'),
        ),
        migrations.AddField(
            model_name='curriculomodel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
