# Generated by Django 2.2.3 on 2019-07-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('1', 'CANDIDATO'), ('2', 'GESTOR')], default='1', max_length=10, verbose_name='Tipo'),
        ),
    ]
