# Generated by Django 2.2.3 on 2019-07-04 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_curriculomodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculomodel',
            name='birth',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Idade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculomodel',
            name='cel',
            field=models.CharField(default=9999999999, max_length=14, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculomodel',
            name='genre',
            field=models.CharField(choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Outro')], default='1', max_length=10, verbose_name='Gênero'),
            preserve_default=False,
        ),
    ]
