# Generated by Django 2.2.3 on 2019-07-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20190704_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculomodel',
            name='birth',
            field=models.IntegerField(verbose_name='Idade'),
        ),
    ]
